[build]
  command = "npm run build"
  publish = "dist/"

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild" # Ensures esbuild is used for bundling Netlify functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200